//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnionWallet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public short Type { get; set; }
        public short Level { get; set; }
        public string Message { get; set; }
        public long UserID { get; set; }
    }
}
