//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnionWallet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnionUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnionUser()
        {
            this.VisitorLogs = new HashSet<VisitorLog>();
        }
    
        public long OnionUserID { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.Guid PasswordSaltGUID { get; set; }
        public bool IsActive { get; set; }
        public bool IsMailing { get; set; }
        public bool IsEmailConfirmed { get; set; }
        public System.Guid EmailConfirmationGUID { get; set; }
        public System.Guid RecoveryGUID { get; set; }
        public string OnionAddress { get; set; }
        public bool DoLogIpAddresses { get; set; }
        public Nullable<System.Guid> TwoFactorGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorLog> VisitorLogs { get; set; }
    }
}
