//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnionWallet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public long VisitorLogID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long OnionUserID { get; set; }
        public string IpAddress { get; set; }
    
        public virtual OnionUser OnionUser { get; set; }
    }
}
